### ISSUE TITLE
#15 Forget Password & Reset password

### ISSUE THREAD

**Issue by u7368347XinyueLi** [Wei2903/ShrineWeb#28]
- Forgot Password:
Implement a "Forgot Password" functionality that allows users and creators to request a password reset link. When users provide their registered email, they should receive an email containing a secure link to reset their password.
- Reset Password:
Once users click the reset password link, direct them to a secure page where they can set a new password. Ensure that this process requires proper authentication (e.g., through a token) to prevent unauthorized access to account settings.

**Comment by GiteonCaulfied** [comment]
Forget Password & Reset password are both implemented by now.
